name: main
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      httpbin:
        image: kennethreitz/httpbin

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Maven Tests
        env:
          DATABASE_URL: postgresql://postgres:5432/postgres?user=postgres&password=postgres
          HTTPBIN_URL: http://httpbin
        run: ./mvnw test
